### ISSUE TITLE
Entity list address

### ISSUE THREAD

**Issue by TANIAX** [lindell/Rocket-League-Ranking-Tracker#1]
Hi, great job man !

Can you share the entity list address ? 

CE keep crash when i try to find out what's writte to an address !

**Comment by lindell** [comment]
This repo has unfortunately not been updated in many year and any old pointer lists are guaranteed to not work.

If you are interested in the pointers of a 6 year old version of the game, this is it, further than that I'm not able to help you:
https://github.com/lindell/Rocket-League-Ranking-Tracker/blob/master/Rocket%20League%20Ranking%20Tracker/Model/Pointers/RocketLeague.CT
